name: CI

on:
  push:
    branches: 
        - main 


jobs:
  Build-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Echo Text
        run: echo "Hello, World!"

