on:
  push:
    branches:
      - master
      - dev
    paths:
      - "src/**"

  pull_request:
    branches:
      - master
      - dev
   
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.2
        
        - name: Run Tests
          run: npm test